[package]
name = "qaly-test"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[[bin]]
name = "qaly-test"
path = "src/main.rs"

[dependencies]
qaly-core = { git = "https://github.com/qaly-dev/qaly-core", tag = "v0.3.0" }
clap.workspace = true
anyhow.workspace = true
